### ISSUE TITLE
Using `resample_reduce` on a `Dataset` with more than one data variable produces incorrect results

### ISSUE THREAD

**Issue by spencerkclark** [dcherian/dask_groupby#35]
Forgive me if I'm too eager to use this package -- I'm excited about the concepts behind it!  I noticed some unusual behavior when using `resample_reduce`.  For some reason it seems like it uses the values of the last data variable for all data variables in the resultant Dataset.  

See the following minimal example:

```
>>> import pandas as pd; import xarray as xr; from dask_groupby.xarray import resample_reduce
>>>
>>> times = pd.date_range("2000", periods=5)
>>> foo = xr.DataArray(range(5), dims=["time"], coords=[times], name="foo")
>>> bar = xr.DataArray(range(1, 6), dims=["time"], coords=[times], name="bar")
>>> ds = xr.merge([foo, bar]).chunk({"time": 4})
>>> resampler = ds.resample(time="4D")
>>> expected = resampler.mean().compute()
>>> result = resample_reduce(resampler, "mean").compute()
>>>
>>>
>>> expected
<xarray.Dataset>
Dimensions:  (time: 2)
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-05
Data variables:
    foo      (time) float64 1.5 4.0
    bar      (time) float64 2.5 5.0
>>> result
<xarray.Dataset>
Dimensions:  (time: 2)
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-05
Data variables:
    foo      (time) float64 2.5 5.0
    bar      (time) float64 2.5 5.0
```

**Comment by dcherian** [comment]
> Forgive me if I'm too eager to use this package -- I'm excited about the concepts behind it!

Thanks @spencerkclark this is great. I am excited too. See #34 for more exciting stuff!

That said there are clearly bugs. I've only run xarray's `groupby` tests so `resample` and `groupby_bins` operations are quite buggy.

This bug is quite bad. If I remove the `compute` call for `result`; then `result.foo.compute()` and `result.bar.compute()` work but `dask.compute(result.foo.data, result.bar.data)` fails as you show. I think I've messed up some dask tokens somewhere.
